version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "dynamic-framework/dynamic-framework-team"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      security-fixes:
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"