version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "@dynamic-framework/ui-react"
    ignore:
      - dependency-name: "@dynamic-framework/ui-react"
        update-types:
          - version-update:semver-major
    groups:
      react-ui:
        patterns:
          - "@dynamic-framework/ui-react*"
        update-types:
          - minor
          - patch